server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update
    showSql: true

security:
  oauth2:
    jwt:
      signkey: 123@#$
#    authorization:
#      jwt:
#        key-alias: oauth2jwt
#        key-store: classpath:/oauth2jwt.jks
#        key-password: oauth2jwtpass
#        key-store-password: oauth2jwtpass